name: flutter_censor_it
description: "A Flutter widget for censoring text with customizable profanity patterns."
version: 2.0.0
repository: https://github.com/pavluke/flutter_censor_it
issue_tracker: https://github.com/pavluke/flutter_censor_it/issues

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  censor_it: ^2.0.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
